# Generated by Django 5.0.2 on 2024-04-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'Магазина',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pars_settings.shop', verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
