# Generated by Django 5.0.2 on 2024-04-19 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars_settings', '0002_shop_article_name_article_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_page',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Текущий номер страницы'),
        ),
        migrations.AddField(
            model_name='position',
            name='target_page',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Целевой номер страницы'),
        ),
        migrations.AddField(
            model_name='query',
            name='target_page',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Целевой номер страницы'),
        ),
        migrations.AlterField(
            model_name='position',
            name='target_position',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Целевая позиция'),
        ),
        migrations.AlterField(
            model_name='query',
            name='target_position',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Целевая позиция'),
        ),
    ]
