# Generated by Django 5.0.2 on 2024-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars_settings', '0003_position_current_page_position_target_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Код'),
        ),
    ]
