# Generated by Django 5.0.2 on 2024-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
