# Generated by Django 5.0.2 on 2024-04-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0002_telegramuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram пользователь', 'verbose_name_plural': 'Telegram пользователи'},
        ),
    ]
